SIGNATURE_METHOD_HMAC = u"HMAC-SHA1"
SIGNATURE_METHOD_RSA = u"RSA-SHA1"
SIGNATURE_METHOD_PLAINTEXT = u"PLAINTEXT"
SIGNATURE_METHODS = (
    SIGNATURE_METHOD_HMAC,
    SIGNATURE_METHOD_RSA,
    SIGNATURE_METHOD_PLAINTEXT,
)

SIGNATURE_TYPE_AUTH_HEADER = u'AUTH_HEADER'
SIGNATURE_TYPE_QUERY = u'QUERY'
SIGNATURE_TYPE_BODY = u'BODY'
SIGNATURE_TYPES = (
    SIGNATURE_TYPE_AUTH_HEADER,
    SIGNATURE_TYPE_QUERY,
    SIGNATURE_TYPE_BODY,
)

CONTENT_TYPE_FORM_URLENCODED = u'application/x-www-form-urlencoded'
CONTENT_TYPES = (
    CONTENT_TYPE_FORM_URLENCODED,
)

